import type { ComponentType, CSSProperties } from 'react';
import {
  ArrowRightLeft,
  Banknote,
  Bed,
  Beer,
  Book,
  Briefcase,
  Building,
  Cake,
  Car,
  Clapperboard,
  Coffee,
  CreditCard,
  Droplet,
  Dumbbell,
  Film,
  Folder,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  Laptop,
  Minus,
  MoreHorizontal,
  Music,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plus,
  Receipt,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Stethoscope,
  Tag,
  Train,
  TrendingUp,
  Tv,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from 'lucide-react';

export type CategoryIconComponent = ComponentType<{ className?: string; style?: CSSProperties }>;

export const CATEGORY_ICONS = [
  'Utensils', 'ShoppingCart', 'Car', 'Fuel', 'Train', 'ShoppingBag', 'Shirt', 'Laptop', 'Home',
  'Film', 'Tv', 'Clapperboard', 'Gamepad2', 'Receipt', 'Zap', 'Droplet', 'Wifi', 'Phone', 'Building',
  'Heart', 'Stethoscope', 'Pill', 'Shield', 'Dumbbell', 'TrendingUp', 'Briefcase', 'PiggyBank',
  'ArrowRightLeft', 'Plus', 'Minus', 'MoreHorizontal', 'Wallet', 'CreditCard', 'Banknote',
  'Coffee', 'Pizza', 'Cake', 'Beer', 'Gift', 'Plane', 'Bed', 'Music', 'Book', 'GraduationCap',
  'Tag', 'Folder',
] as const;

const categoryIconMap: Record<string, CategoryIconComponent> = {
  Utensils,
  ShoppingCart,
  Car,
  Fuel,
  Train,
  ShoppingBag,
  Shirt,
  Laptop,
  Home,
  Film,
  Tv,
  Clapperboard,
  Gamepad2,
  Receipt,
  Zap,
  Droplet,
  Wifi,
  Phone,
  Building,
  Heart,
  Stethoscope,
  Pill,
  Shield,
  Dumbbell,
  TrendingUp,
  Briefcase,
  PiggyBank,
  ArrowRightLeft,
  Plus,
  Minus,
  MoreHorizontal,
  Wallet,
  CreditCard,
  Banknote,
  Coffee,
  Pizza,
  Cake,
  Beer,
  Gift,
  Plane,
  Bed,
  Music,
  Book,
  GraduationCap,
  Tag,
  Folder,
};

export function getCategoryIcon(iconName?: string | null): CategoryIconComponent {
  if (!iconName) return Tag;
  return categoryIconMap[iconName] || Tag;
}
